#!/bin/sh

while read file
do
        fullpath='$(pwd)/$file'
        case "$1" in
        "w")
                cp "$file" ~/.config/wall.png &&
                xwallpaper --zoom "$HOME/.config/wall.png" ;;
                #notify-send -i "$HOME/.config/wall.jpg" "Wallpaper changed" ;;
        esac
done
